spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fdmbase?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ceobigin123

  flyway:
    enabled: true
    locations: classpath:db/migration